black and isort scripts dir too (retrigger test due to unclear failure error)
```
(line   38) ok        https://github.com/SeldonIO/seldon-core/issues/1344
writing output... [100%] wrappers/s2i

(line   32) -ignored- ../python/README.md

build finished with problems, 9 warnings.
make: [Makefile:33: linkcheck] Error 1 (ignored)
! grep -v '429' _build/output.txt | grep 'broken'
examples/pachyderm-simple.nblink:11: [broken] https://pachyderm.io/: HTTPSConnectionPool(host='www.pachyderm.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'www.pachyderm.com' doesn't match either of '*.netlify.com', 'netlify.com'",),))
make: *** [Makefile:34: linkcheck] Error 1
make: Leaving directory '/__w/seldon-core/seldon-core/doc'
Error: Process completed with exit code 2.
```